INSERT INTO countries (country,
 development_level,
 poverty_rate_percent,
 internet_infrastructure_index,
 average_internet_speed_mbps)
SELECT 
 country,
 development_level,
 poverty_rate_percent,
 internet_infrastructure_index,
 average_internet_speed_mbps
 FROM mixed GROUP BY country order by country;


INSERT INTO students (
    country_id,
    country,
    student_id,
    age,
    gender,
    urban_rural,
    family_income_level,
    device_access,
    internet_access_hours,
    education_level,
    field_of_study,
    academic_motivation,
    online_learning_hours,
    social_media_hours,
    sessions_per_day,
    average_session_length_minutes,
    late_night_usage,
    education_content_hours,
    short_video_hours,
    entertainment_content_hours,
    news_content_hours,
    likes_given_per_day,
    comments_written_per_day,
    posts_created_per_week,
    late_night_score,
    brain_rot_index,
    brain_rot_level,
    attention_span_minutes,
    study_hours_per_week,
    class_attendance_rate,
    productivity_score,
    sleep_hours,
    stress_level,
    anxiety_score,
    depression_score,
    ads_viewed_per_day,
    ads_clicked_per_week,
    impulse_purchase_score,
    digital_spending_per_month,
    cyberbullying_exposure,
    adult_content_exposure,
    digital_addiction_score,
    wellbeing_index,
    academic_risk_score,
    financial_risk_score
)
SELECT c.country_id, c.country,
    m.student_id,
    m.age,
    m.gender,
    m.urban_rural,
    m.family_income_level,
    m.device_access,
    m.internet_access_hours,
    m.education_level,
    m.field_of_study,
    m.academic_motivation,
    m.online_learning_hours,
    m.social_media_hours,
    m.sessions_per_day,
    m.average_session_length_minutes,
    m.late_night_usage,
    m.education_content_hours,
    m.short_video_hours,
    m.entertainment_content_hours,
    m.news_content_hours,
    m.likes_given_per_day,
    m.comments_written_per_day,
    m.posts_created_per_week,
    m.late_night_score,
    m.brain_rot_index,
    m.brain_rot_level,
    m.attention_span_minutes,
    m.study_hours_per_week,
    m.class_attendance_rate,
    m.productivity_score,
    m.sleep_hours,
    m.stress_level,
    m.anxiety_score,
    m.depression_score,
    m.ads_viewed_per_day,
    m.ads_clicked_per_week,
    m.impulse_purchase_score,
    m.digital_spending_per_month,
    m.cyberbullying_exposure,
    m.adult_content_exposure,
    m.digital_addiction_score,
    m.wellbeing_index,
    m.academic_risk_score,
    m.financial_risk_score
FROM mixed m
JOIN countries c ON m.country = c.country;

ALTER TABLE students
DROP COLUMN country;

