DROP TABLE IF EXISTS students;
CREATE TABLE students (
    "country_id" INT,
    "student_id" INTEGER,
    "country" TEXT,
    "age" INT,
    "gender" TEXT CHECK(gender IS NULL OR gender IN ('Male','Female','Other')),
    "urban_rural" TEXT CHECK(urban_rural IS NULL OR urban_rural IN ('Urban', 'Rural')),
    "family_income_level" TEXT CHECK(family_income_level IS NULL OR family_income_level IN ('High','Low','Middle')),
    "device_access" TEXT CHECK(device_access IS NULL OR device_access IN ('Smartphone','Laptop','Both','Shared Device')),
    "internet_access_hours" DECIMAL,
    "education_level" TEXT CHECK (education_level IS NULL OR education_level IN ('School','Dropout','Postgraduate','PhD','Diploma','Graduate')),
    "field_of_study" TEXT,
    "academic_motivation" DECIMAL,
    "online_learning_hours" DECIMAL,
    "social_media_hours" DECIMAL,
    "sessions_per_day" DECIMAL,
    "average_session_length_minutes" DECIMAL,
    "late_night_usage" TEXT CHECK(late_night_usage IS NULL OR late_night_usage IN ('Sometimes','Never','Often','Always')),
    "education_content_hours" DECIMAL,
    "short_video_hours" DECIMAL,
    "entertainment_content_hours" DECIMAL,
    "news_content_hours" DECIMAL,
    "likes_given_per_day" DECIMAL,
    "comments_written_per_day" DECIMAL,
    "posts_created_per_week" DECIMAL,
    "late_night_score" INT,
    "brain_rot_index" DECIMAL,
    "brain_rot_level" TEXT,
    "attention_span_minutes" DECIMAL,
    "study_hours_per_week" DECIMAL,
    "class_attendance_rate" DECIMAL,
    "productivity_score" DECIMAL,
    "sleep_hours" DECIMAL,
    "stress_level" DECIMAL,
    "anxiety_score" DECIMAL,
    "depression_score" DECIMAL,
    "ads_clicked_per_week" DECIMAL,
    "ads_viewed_per_day" DECIMAL,
    "impulse_purchase_score" DECIMAL,
    "digital_spending_per_month" DECIMAL,
    "cyberbullying_exposure" TEXT CHECK (cyberbullying_exposure IS NULL OR cyberbullying_exposure IN ('Yes','No')),
    "adult_content_exposure" TEXT CHECK (adult_content_exposure IS NULL OR adult_content_exposure IN ('Yes','No')),
    "digital_addiction_score" DECIMAL,
    "wellbeing_index" DECIMAL,
    "academic_risk_score" INT,
    "financial_risk_score" DECIMAL,
    PRIMARY KEY (student_id),
    FOREIGN KEY (country_id) REFERENCES countries(country_id)
);

DROP TABLE IF EXISTS countries;
CREATE TABLE countries (
    "country_id" INTEGER,
    "country" TEXT,
    "development_level" TEXT CHECK (development_level IS NULL OR development_level IN ('Developed','Developing', 'Underdeveloped')),
    "poverty_rate_percent" DECIMAL,
    "internet_infrastructure_index" DECIMAL,
    "average_internet_speed_mbps" DECIMAL,
    PRIMARY KEY (country_id)
);


DROP TABLE IF EXISTS mixed;
CREATE TABLE mixed (
    "student_id" INTEGER,
    "country" TEXT,
    "development_level" TEXT CHECK (development_level IS NULL OR development_level IN ('Developed','Developing', 'Underdeveloped')),
    "poverty_rate_percent" DECIMAL,
    "internet_infrastructure_index" DECIMAL,
    "average_internet_speed_mbps" DECIMAL,
    "age" INT,
    "gender" TEXT CHECK(gender IS NULL OR gender IN ('Male','Female','Other')),
    "urban_rural" TEXT CHECK(urban_rural IS NULL OR urban_rural IN ('Urban', 'Rural')),
    "family_income_level" TEXT CHECK(family_income_level IS NULL OR family_income_level IN ('High','Low','Middle')),
    "device_access" TEXT CHECK(device_access IS NULL OR device_access IN ('Smartphone','Laptop','Both','Shared Device')),
    "internet_access_hours" DECIMAL,
    "education_level" TEXT CHECK (education_level IS NULL OR education_level IN ('School','Dropout','Postgraduate','PhD','Diploma','Graduate')),
    "field_of_study" TEXT,
    "academic_motivation" DECIMAL,
    "online_learning_hours" DECIMAL,
    "social_media_hours" DECIMAL,
    "sessions_per_day" DECIMAL,
    "average_session_length_minutes" DECIMAL,
    "late_night_usage" TEXT CHECK(late_night_usage IS NULL OR late_night_usage IN ('Sometimes','Never','Often','Always')),
    "education_content_hours" DECIMAL,
    "short_video_hours" DECIMAL,
    "entertainment_content_hours" DECIMAL,
    "news_content_hours" DECIMAL,
    "likes_given_per_day" DECIMAL,
    "comments_written_per_day" DECIMAL,
    "posts_created_per_week" DECIMAL,
    "late_night_score" INT,
    "brain_rot_index" DECIMAL,
    "brain_rot_level" TEXT,
    "attention_span_minutes" DECIMAL,
    "study_hours_per_week" DECIMAL,
    "class_attendance_rate" DECIMAL,
    "productivity_score" DECIMAL,
    "sleep_hours" DECIMAL,
    "stress_level" DECIMAL,
    "anxiety_score" DECIMAL,
    "depression_score" DECIMAL,
    "ads_clicked_per_week" DECIMAL,
    "ads_viewed_per_day" DECIMAL,
    "impulse_purchase_score" DECIMAL,
    "digital_spending_per_month" DECIMAL,
    "cyberbullying_exposure" TEXT CHECK (cyberbullying_exposure IS NULL OR cyberbullying_exposure IN ('Yes','No')),
    "adult_content_exposure" TEXT CHECK (adult_content_exposure IS NULL OR adult_content_exposure IN ('Yes','No')),
    "digital_addiction_score" DECIMAL,
    "wellbeing_index" DECIMAL,
    "academic_risk_score" INT,
    "financial_risk_score" DECIMAL,
    PRIMARY KEY (student_id)
);

